# Generated by Django 5.2 on 2025-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_auto_20250614_2346"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="Default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The permissions this user has.",
                related_name="customer_permission",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
    ]
