# Generated by Django 5.2 on 2025-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_streaming", "0002_alter_playlist_user_alter_recommendations_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendations",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
