# Generated by Django 5.2 on 2025-07-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_streaming", "0003_recommendations_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(
                related_name="playlists", to="music_streaming.song"
            ),
        ),
    ]
